version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379

  consul:
    image: hashicorp/consul
    ports:
      - 8500:8500
  
  grafana:
    image: grafana/grafana-enterprise
    volumes:
      - storage:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  
  nginx:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8888:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  
  mysql:
    image: mysql
    volumes:
      - storage:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456

volumes:
  storage: {}
