version: '3.4'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379
